version: '3.5'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - .:/homebridge/maxvapor-plugin
    ports:
      - "8581:8581"
